class wednesday::applications::mac {
  include alfred
  include arq
  include brow
  include btsync
  include caffeine
  include ccleaner
  include charles
  include chrome
  include cyberduck
  include dropbox
  include evernote
  include firefox
  include flux
  include googledrive
  include googleearth
  include handbrake
  include harvest
  include iterm2::stable
  include induction
  include opera
  include tower
  include transmit
  include screenhero
  include sequel_pro
  include spectacle
  include skitch
  include skype
  include spotify
  include sublime_text_2
  include textwrangler
  include vagrant
  include virtualbox
  include vlc
}